### ISSUE TITLE
server stop connect 一分钟之内server就不收发了

### ISSUE THREAD

**Issue by tiax615** [feixuwu/UEWebsocket#79]
server stop connect in 1min

i use python to build a server with websockets, error like this:

```
Task exception was never retrieved
future: <Task finished coro=<consumer_handler() done, defined at e:/proj_ue4/AdasSim3/PythonApi/WebsocketTest.py:9> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "C:\Users\Minieye_Caidu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 796, in transfer_data
    message = await self.read_message()
  File "C:\Users\Minieye_Caidu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 864, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Users\Minieye_Caidu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 939, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Users\Minieye_Caidu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 1019, in read_frame
    extensions=self.extensions,
  File "C:\Users\Minieye_Caidu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\framing.py", line 121, in read
    data = await reader(2)
  File "C:\Users\Minieye_Caidu\AppData\Local\Programs\Python\Python37\lib\asyncio\streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:/proj_ue4/AdasSim3/PythonApi/WebsocketTest.py", line 10, in consumer_handler
    async for message in websocket:
  File "C:\Users\Minieye_Caidu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 414, in __aiter__
    yield await self.recv()
  File "C:\Users\Minieye_Caidu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 485, in recv
    await self.ensure_open()
  File "C:\Users\Minieye_Caidu\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 772, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

ue4 dont show any error

thank all

**Comment by feixuwu** [comment]
gc问题，你的socket对象被回收了，当产量存储到level或者gamemode里，在同一关卡不会被回收了

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by tiax615** [comment]
It's really a gc problem, and the existence of a variable will work just fine. Thank you!

确实是gc问题，存在一个变量里就可以正常工作了。感谢！
